let shopItemsData = [
  {
    id: "dairy1",
    name: "Milk",
    price: 22,
    desc: "Rs 22 per Litre",
    img: "/src/pics/picsDairy/milk.png",
  },
  {
    id: "dairy2",
    name: "Paneer",
    price: 300,
    desc: "Rs 300 Per Kilo",
    img: "/src/pics/picsDairy/paneer.png",
  },
  {
    id: "dairy3",
    name: "Curd",
    price: 40,
    desc: "Rs 40 Per litre",
    img: "/src/pics/picsDairy/curd.png",
  },
  {
    id: "dairy4",
    name: "Ghee",
    price: 520,
    desc: "Rs 520 Per Litre",
    img: "/src/pics/picsDairy/ghee.png",
  },
  {
    id: "dairy5",
    name: "Vanilla Ice Cream",
    price: 180,
    desc: "Rs 180 Per Litre",
    img: "/src/pics/picsDairy/icecream.png",
  },
  {
    id: "dairy6",
    name: "Milk Chocolate",
    price: 110,
    desc: "Rs 110 Per Litre",
    img: "/src/pics/picsDairy/mchocolate.png",
  },
  {
    id: "dairy7",
    name: "Buttermilk",
    price: 70,
    desc: "Rs 70 Per Litre",
    img: "/src/pics/picsDairy/buttermilk.png",
  },
  {
    id: "dairy8",
    name: "Cheese",
    price: 515,
    desc: "Rs 515 Per Kilo",
    img: "/src/pics/picsDairy/cheese.png",
  },
  {
    id: "dairy9",
    name: "Butter",
    price: 425,
    desc: "Rs 425 Per Kilo",
    img: "/src/pics/picsDairy/butter.png",
  },
  {
    id: "dairy10",
    name: "Whipped Cream",
    price: 71,
    desc: "Rs 71 for 250ml",
    img: "/src/pics/picsDairy/cream.png",
  },
  {
    id: "dairy11",
    name: "Milkshake",
    price: 570,
    desc: "Rs 570 Per Litre",
    img: "/src/pics/picsDairy/milkshake.png",
  },
  {
    id: "fruit1",
    name: "Spinach",
    price: 12,
    desc: "Rs 12 per Bunch",
    img: "/src/pics/picsFruit/spinach.png",
  },
  {
    id: "fruit2",
    name: "Tomato",
    price: 18,
    desc: "Rs 18 Per Kilo",
    img: "/src/pics/picsFruit/tomato.png",
  },
  {
    id: "fruit3",
    name: "Mushroom",
    price: 60,
    desc: "Rs 40 Per box(8 pieces)",
    img: "/src/pics/picsFruit/mushroom.png",
  },
  {
    id: "fruit4",
    name: "Curry leaf",
    price: 20,
    desc: "Rs 20 Per 100 gm",
    img: "/src/pics/picsFruit/curryleaf.png",
  },
  {
    id: "fruit5",
    name: "Cauliflower",
    price: 20,
    desc: "Rs 20 Per Piece",
    img: "/src/pics/picsFruit/cauliflower.png",
  },
  {
    id: "fruit6",
    name: "Onions",
    price: 30,
    desc: "Rs 30 Per Kilo",
    img: "/src/pics/picsFruit/onion.png",
  },
  {
    id: "fruit7",
    name: "Apples",
    price: 70,
    desc: "Rs 70 Per Kilo",
    img: "/src/pics/picsFruit/apple.png",
  },
  {
    id: "fruit8",
    name: "Banana",
    price: 50,
    desc: "Rs 50 4 a Bunch",
    img: "/src/pics/picsFruit/banana.png",
  },
  {
    id: "fruit9",
    name: "Strawberry",
    price: 140,
    desc: "Rs 140 Per Box",
    img: "/src/pics/picsFruit/strawberry.png",
  },
  {
    id: "fruit10",
    name: "Orange",
    price: 80,
    desc: "Rs 80 for 6 pieces",
    img: "/src/pics/picsFruit/orange.png",
  },
  {
    id: "fruit11",
    name: "Sugarcane",
    price: 7,
    desc: "Rs 7 Per Piece",
    img: "/src/pics/picsFruit/sugarcane.png",
  },
  {
    id: "fruit12",
    name: "Guava",
    price: 75,
    desc: "Rs 75 Per Kilo",
    img: "/src/pics/picsFruit/guava.png",
  },
  {
    id: "meat1",
    name: "Tuna Fish",
    price: 250,
    desc: "Rs 250 Per Kilo",
    img: "/src/pics/picsMeat/fish1.png",
  },
  {
    id: "meat2",
    name: "Bengali Hilsa Fish",
    price: 2600,
    desc: "Rs 2600 Per Kilo",
    img: "/src/pics/picsMeat/fish2.png",
  },
  {
    id: "meat3",
    name: "Shrimp",
    price: 1300,
    desc: "Rs 1300 Per Kilo",
    img: "/src/pics/picsMeat/shrimp.png",
  },
  {
    id: "meat4",
    name: "Chicken",
    price: 180,
    desc: "Rs 180 Per Kilo",
    img: "/src/pics/picsMeat/chicken.png",
  },
  {
    id: "meat5",
    name: "Lamb",
    price: 600,
    desc: "Rs 600 Per Kilo",
    img: "/src/pics/picsMeat/lamb.png",
  },
  {
    id: "meat6",
    name: "Crab sticks",
    price: 210,
    desc: "Rs 210 for 250 gm",
    img: "/src/pics/picsMeat/crab.png",
  },
  {
    id: "meat7",
    name: "Egg",
    price: 95,
    desc: "Rs 95 a Dozen",
    img: "/src/pics/picsMeat/egg.png",
  },
  {
    id: "meat8",
    name: "Spiced Sausage",
    price: 130,
    desc: "Rs 130 per 180 gm",
    img: "/src/pics/picsMeat/sausage.png",
  },
  {
    id: "meat9",
    name: "Chicken popcorn ",
    price: 300,
    desc: "Rs 300 ",
    img: "/src/pics/picsMeat/chickenpopcorn.png",
  },
  {
    id: "meat10",
    name: "Grilled chicken Patty",
    price: 310,
    desc: "Rs 310 ",
    img: "/src/pics/picsMeat/chickenpatty2.png",
  },
  {
    id: "meat11",
    name: "Fish Finger",
    price: 400,
    desc: "Rs 400 ",
    img: "/src/pics/picsMeat/fishfinger.png",
  },
  {
    id: "meat12",
    name: "Mutton Keema",
    price: 400,
    desc: "Rs 400 for 300gm",
    img: "/src/pics/picsMeat/keema.png",
  },
  {
    id: "cond1",
    name: "Olive oil",
    price: 1050,
    desc: "Rs 1050 Per Litre",
    img: "/src/pics/picsCond/oil.png",
  },
  {
    id: "cond2",
    name: "Vinegar",
    price: 60,
    desc: "Rs 60 Per 200ml",
    img: "/src/pics/picsCond/vinegar.png",
  },
  {
    id: "cond3",
    name: "Sundried Chilli",
    price: 160,
    desc: "Rs 160 Per 100gm",
    img: "/src/pics/picsCond/chilli.png",
  },
  {
    id: "cond4",
    name: "Mustard Sauce",
    price: 120,
    desc: "Rs 120 Per 100 ml",
    img: "/src/pics/picsCond/mustard.png",
  },
  {
    id: "cond5",
    name: "Oregano Seasoning",
    price: 200,
    desc: "Rs 200 Per 100gm",
    img: "/src/pics/picsCond/oregano.png",
  },
  {
    id: "cond6",
    name: "Chaat Masala",
    price: 75,
    desc: "Rs 75 Per 100gm",
    img: "/src/pics/picsCond/chaat.png",
  },
  {
    id: "cond7",
    name: "Black pepper",
    price: 150,
    desc: "Rs 150 Per 100gm",
    img: "/src/pics/picsCond/pepper.png",
  },
  {
    id: "cond8",
    name: "Soya Sauce",
    price: 475,
    desc: "Rs 475 Per 100ml",
    img: "/src/pics/picsCond/soya.png",
  },
  {
    id: "cond9",
    name: "Wild honey",
    price: 300,
    desc: "Rs 300 Per 250gm",
    img: "/src/pics/picsCond/honey.png",
  },
  {
    id: "cond10",
    name: "Vanilla Essence",
    price: 70,
    desc: "Rs 70 Per 30ml",
    img: "/src/pics/picsCond/vessence.png",
  },
  {
    id: "cond11",
    name: "Lemon grass",
    price: 270,
    desc: "Rs 270 Per 100gm",
    img: "/src/pics/picsCond/lemongrass.png",
  },
  {
    id: "cond12",
    name: "Cinnamon",
    price: 110,
    desc: "Rs 110 Per 100gm",
    img: "/src/pics/picsCond/cinnamon.png",
  },
  {
    id: "millet1",
    name: "Basmati Rice",
    price: 140,
    desc: "Rs 140 Per Kilo",
    img: "/src/pics/picsMillet/rice.png",
  },
  {
    id: "millet2",
    name: "Multi Grain Atta",
    price: 70,
    desc: "Rs 70 Per Kilo",
    img: "/src/pics/picsMillet/wheat.png",
  },
  {
    id: "millet3",
    name: "Oats",
    price: 165,
    desc: "Rs 165 Per Kilo",
    img: "/src/pics/picsMillet/oats.png",
  },
  {
    id: "millet4",
    name: "Sprouts",
    price: 18,
    desc: "Rs 18 Per 100 gm",
    img: "/src/pics/picsMillet/sprouts.png",
  },
  {
    id: "millet5",
    name: "Pink Salt",
    price: 110,
    desc: "Rs 110 Per Kilo",
    img: "/src/pics/picsMillet/salt.png",
  },
  {
    id: "millet6",
    name: "ID Special",
    price: 75,
    desc: "Rs 75 Per packet",
    img: "/src/pics/picsMillet/batter.png",
  },
  {
    id: "millet7",
    name: "Maida",
    price: 100,
    desc: "Rs 100 Per Kilo",
    img: "/src/pics/picsMillet/maida.png",
  },
  {
    id: "millet8",
    name: "Brown rice",
    price: 150,
    desc: "Rs 150 Per Kilo",
    img: "/src/pics/picsMillet/brownrice.png",
  },
  {
    id: "millet9",
    name: "Vermicelli",
    price: 260,
    desc: "Rs 260 ",
    img: "/src/pics/picsMillet/vermicelli.png",
  },
  {
    id: "millet10",
    name: "Penne Wheat Pasta",
    price: 250,
    desc: "Rs 250 Per 500 gm",
    img: "/src/pics/picsMillet/pasta.png",
  },
  {
    id: "millet11",
    name: "Wheat Noodles",
    price: 270,
    desc: "Rs 270 ",
    img: "/src/pics/picsMillet/noodles.png",
  },
  {
    id: "millet12",
    name: "Sabudana",
    price: 260,
    desc: "Rs 260 ",
    img: "/src/pics/picsMillet/sabudana.png",
  },
  {
    id: "snacks1",
    name: "Ferrero Rocher",
    price: 750,
    desc: "Rs 750 Big packet",
    img: "/src/pics/picsSnacks/chocolate.png",
  },
  {
    id: "snacks2",
    name: "Hide n Seek",
    price: 30,
    desc: "Rs 30 ",
    img: "/src/pics/picsSnacks/biscuit.png",
  },
  {
    id: "snacks3",
    name: "Papad",
    price: 80,
    desc: "Rs 80 ",
    img: "/src/pics/picsSnacks/papad.png",
  },
  {
    id: "snacks4",
    name: "Lays Chips",
    price: 20,
    desc: "Rs 20 ",
    img: "/src/pics/picsSnacks/chips.png",
  },
  {
    id: "snacks5",
    name: "Choco Chip Muffin",
    price: 65,
    desc: "Rs 65 ",
    img: "/src/pics/picsSnacks/muffin.png",
  },
  {
    id: "snacks6",
    name: "Popcorn",
    price: 150,
    desc: "Rs 150 ",
    img: "/src/pics/picsSnacks/popcorn.png",
  },
  {
    id: "snacks7",
    name: "Dry Fruits Gift Pack",
    price: 850,
    desc: "Rs 850 ",
    img: "/src/pics/picsSnacks/dryfruit.png",
  },
  {
    id: "snacks8",
    name: "Samosa",
    price: 295,
    desc: "Rs 295 ",
    img: "/src/pics/picsSnacks/samosa.png",
  },
  {
    id: "snacks9",
    name: "Fruit Cake",
    price: 150,
    desc: "Rs 150 for 200 gm",
    img: "/src/pics/picsSnacks/cake.png",
  },  
  {
    id: "snacks10",
    name: "Nachos",
    price: 190,
    desc: "Rs 190 for 200gm",
    img: "/src/pics/picsSnacks/nachos.png",
  },
];

